
default: &default
  adapter: mysql2
  encoding: utf8
  host: localhost
  port: 3306
  username: root
  password: 

development:
  <<: *default
  database: diary_development

test:
  <<: *default
  database: diary_test


